languageCode = "en"
languageName = "English"
languageDirection = "ltr"
weight = 1

title = "dazjones.github.io"
copyright = "&copy; 2024 dazjones.github.io"

[params]
  dateFormat = "2 January 2006"

  mainSections = ["profile"]
  description = "My personal space."

[params.author]
  name = "Darren Jones"
  image = "img/author.jpg"
  headline = ""
  bio = "Husband, tinkerer, leader. Safest leaving the code to others..."
  links = [
    { linkedin = "https://www.linkedin.com/in/dazjones/" },
    { github = "https://github.com/dazjones" },
  ]