[[main]]
  name = "Blog"
  pageRef = "posts"
  weight = 10


[[main]]
  name = "GitHub"
  url = "https://github.com/dazjones/dazjones.github.io"
  weight = 40
  [main.params]
    icon = "github"
    showName = false
    target = "_blank"

[[main]]
  identifier = "appearance"
  weight = 90
  [main.params]
    action = "appearance"

[[main]]
  identifier = "search"
  weight = 99
  [main.params]
    action = "search"
