# Welcome to Jekyll Paper for Github
#
# This is the configuration file for your blog, please change these items after forked.

title: djns.io
email: darren@djns.io
name: Darren Jones
description: >- # this means to ignore newlines until "baseurl:"
  Interested in all things tech
keywords: [Your keywords]
baseurl: '' # the subpath of your site, e.g. /`blog
url: '' # the base hostname & protocol for your site, e.g. http://example.com
domain: 'djns.io' # the domain name for your site, e.g. example.com
language: en

analytics: GTM-TTFLKB86

comments: false # enable comments
disqus: # disqus account

mathjax: false # Math support
diagram: false # Diagrams support

paginate: 25
paginate_path: '/page:num/'

permalink: /:year/:month/:day/:title

sass:
  sass_dir: _sass
  style: expanded

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-seo-tag
