title: djns.io
email: darren@djns.io
name: Darren Jones
description:
keywords: [Darren Jones Technology Leadership Personal Blog]
baseurl: ''
url: 'https://djns.io' 
domain: 'djns.io' 
language: en

analytics: "G-9NMQHR9B2J"

comments: false
disqus:
mathjax: false
diagram: false

paginate: 25
paginate_path: '/page:num/'

permalink: /:year/:month/:day/:title

sass:
  sass_dir: _sass
  style: compressed

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-seo-tag
